export const SET_CURRENT_USER = 'SET_USER';
export const CLEAR_CURRENT_USER = 'CLEAR_USER';

export const SET_SELECTED_TAG = 'SET_SELECTED_TAG';
export const CLEAR_CURRENT_TAG = 'CLEAR_CURRENT_TAG';
export const MONITORED_TAGS_EMPTY = 'MONITORED_TAGS_EMPTY';